version: '3.8'

services:
  postgresql:
    image: postgres:16.1
    container_name: tapply-db
    restart: unless-stopped
    volumes:
      - pg-data:/var/lib/postgresql/data
    env_file:
      - .env-dev
    networks:
      - my-network
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis/redis-stack:7.2.0-v6
    restart: unless-stopped
    env_file:
      - .env-dev
    environment:
      REDIS_ARGS: '--requirepass ${REDIS_PASSWORD}'
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - my-network
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    env_file:
    - .env-dev
    ports:
    - "8081:8081"
    networks:
      - my-network
volumes:
  pg-data:
  pgadmin-data:

networks:
  my-network:
    driver: bridge
