#----------------------- builder ---------------------#
FROM node:20.15.1-alpine AS builder
WORKDIR /app
COPY package.json tsconfig.json ./
RUN npm install
COPY . .
RUN npm run prisma-generate
RUN npm run build
#----------------------- Release ---------------------#
FROM builder AS release
COPY --from=builder /app/node_modules ./node_modules

COPY --from=builder /app/dist ./dist
COPY --from=builder /app/prisma ./prisma
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/.env-dev ./.env

RUN apk add ffmpeg
# & npm prune --omit=dev --verbose --no-interactive
CMD npm run prisma-migrate-deploy && npm run seed-sync && npm run seed && npm run start:migrate:prod

