export enum RoutesEntities {
  PRODUCTS = 'products',
  ORDER_ITEMS = 'order-items',
  AD_BLOCKS = 'ad-blocks',
  APP_CONFIGURATIONS = 'app-configurations',
  CARE_LISTS = 'care-lists',
  CATEGORY_TYPES = 'category-types',
  COLORS = 'colors',
  CUSTOMERS = 'customers',
  COMMENT = 'comment',
  DASHBOARDS = 'dashboards',
  DESIGNS = 'designs',
  FUNCTIONALITIES = 'functionalities',
  ORDERS = 'orders',
  PRODUCTS_ITEMS = 'products-items',
  PROMO_CODES = 'promo-codes',
  PROMOTIONAL_BLOCKS = 'promotional-blocks',
  SEGMENTS = 'segments',
  SHOPS = 'shops',
  SIZES = 'sizes',
  STATISTICS = 'statistics',
  USERS = 'users',
  USERS_PAYMENTS = 'user-payments',
  SUBSCRIBERS_MESSAGES = 'subscribers-messages',
  TEMPLATES = 'templates',
}
